language: node_js

env:
  global:
    - TMPDIR=/tmp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  apt_packages:
    - libgmp-dev

dist: trusty
sudo: required

node_js:
  - "0.10"
  - "4"
 
script:
  - npm test
  - COVERALLS_REPO_TOKEN=uVhUzByLbNQ0yLRqmFMO983nxZFGD55cf npm run report-coverage

notifications:
  email:
    - rfkelly@mozilla.com
